
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Joy Mirembe
# Username: mirembej
#
# Assignment: A03: Fully Functional Gitty Psychedelic Robotic Turtles
# Purpose: drawing something complex, like a house, animal, or person
# Google Doc Link: https://docs.google.com/document/d/1VnycbZDpbMZEk4t8DCkbR_cIkdyzO0EcmOHEaYThhzg/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################


import turtle


def drawFace(t):
    """
    Draws a person's face.
    """

    #drawing the turtle's facial outline
    t.penup()
    t.goto(0, 100)  # making t go up
    t.pendown()

    t.fillcolor(244,164,96)    #t's face is brown
    t.begin_fill()
    t.circle(80)              #drawing t's circular headshape
    t.end_fill()

    #drawing alex's two eyes
    t.up()
    t.goto (-35,210)
    t.pendown()
    t.dot(15, "black")

    t.up()
    t.goto(35, 210)
    t.pendown()
    t.dot(15, "black")

    t.up()
    t.goto(-30,130)
    t.down()
    for i in range(4):
        t.left(6)
        t.forward(15)

    t.left(90)
    t.fd(5)
    t.back(10)


    # ....


def myLegs(t):
    """
    Draws their stick legs with shoes
    """

    turtle.register_shape("url.gif")  # registered the gif so that it can be used
    turtle.register_shape("url 2.gif")  # registered the gif so that it can be used
    t.penup()
    t.goto (-6, -200)
    t.pendown()
    t.shape("url.gif")
    t.stamp()


    #adding daisies!!

    t.penup()
    t.goto(-380, 220)
    t.pendown()
    t.shape("url 2.gif")

    # ...


def main():
    """
    Everything else in the code that doesn't belong to a function
    """
    # ...
    turtle.colormode(255)      #setting the color mode to the rgb mode

    alex = turtle.Turtle()
    wn = turtle.Screen()

    wn.bgcolor(114, 123, 100)    #setting the backgroung of the screen to some random color
    wn.bgpic("my.gif")
    wn.title('My abstract art piece!!!')

    alex.speed(10)                  #making alex a bit faster



    drawFace(alex)            # Function call to function_1
    myLegs(alex)            # Function call to function_2

    wn.exitonclick()

main()



