
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: karakostas Zacharias
# Username: karakostasz
#
# Assignment: A03
# Purpose: CSC 226
# Google Doc Link: https://docs.google.com/document/d/1qw9MNUGLKzGOSEt-z-c50qLjH5rsSSm2Iqx_4XDDflg/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle

def function_1():
    """
    Docstring for function_1
    """
    pass
    # ....


def function_2():
    """
    Docstring for function_2
    """
    pass
    # ...


def main():
    """
    Docstring for main
    """
    # ...
    function_1()            # Function call to function_1
    function_2()            # Function call to function_2


main()


